### ISSUE TITLE
new error from Github webhook: undefined method 'each' for nil:nilClass

### ISSUE THREAD

**Issue by Lwangaman** [matthewjackowski/txgh#3]
I applied the last update, but now the github webhook is getting a new 500 error:

```Puma caught this error: undefined method 'each' for nil:NilClass (NoMethodError)
/app/app/app.rb:81:in 'block in <class:Hooks>'```

If the heroku branch is what should be used for the heroku app, how do I do that? How do I tell the heroku app to use the heroku branch instead of the master branch? I have never used heroku apps before...

**Comment by matthewjackowski** [comment]
Thanks for trying!

So that part of the code is looping through your git web hook status.  The missing class error means to me some expected part of that hook is missing, maybe a commit or a file modification.  The best way I can help is if you log the actual git web hook so that it can be used in a test.
You can see an example of one of my test web hooks [here](https://github.com/matthewjackowski/txgh/blob/master/tests/github_postbody.rb)
I'll leave this issue open to review once you provide a sample web hook.

This will also allow me to make some negative tests and improve the error handling on this project!


As for Heroku setup.  Since with heroku you manage your service via git, what I do is setup a separate tracking branch so I can always review the code I have pushed to Heroku.  Since this is a test instance I might push changes to Heroku just to test out.  

Here are the commands I used to setup my Heroku app:
```
git clone git@github.com:matthewjackowski/txgh.git
cd txgh
git checkout heroku
heroku apps
heroku git:remote -a <NAME OF APP>
git branch --set-upstream heroku heroku/master
```

Now you can make changes, and do commits as usual.  To deploy the code and save a copy to your branch you can now run:

```
git push heroku master
git push origin heroku
```

**Comment by matthewjackowski** [comment]
No updates...closing
